### ISSUE TITLE
Linux Ubuntu issues

### ISSUE THREAD

**Issue by LibeerDev** [CodyMarkix/PetNociuKrtkuse2#10] opened 2023-11-07 10:51 UTC
1. The camera is panned towards the left of the room and moving it right is possible, but it instantly snaps back.

2. Tablet button doesn't open the tablet screen

**Comment by CodyMarkix** [comment] 2023-11-15 10:18
The tablet is by design supposed to open only when the camera is facing the table. (The button is just a visual element, the game checks for when to open the tablet based on cursor position (approx. bottom 560 pixels of the screen))

As for the camera, I'm going to try to replicate the issue and will update you.

**Comment by yesseruser** [comment] 2024-06-25 13:51
No. 1 is an issue on Mac as well (at least in the editor in the source cloned version).

**Comment by yesseruser** [comment] 2024-06-25 14:22
I've created a separate issue for 1. (#13)

**Comment by CodyMarkix** [comment] 2024-06-25 15:12
Fixed via #14

**Closed by CodyMarkix** 2024-06-25 15:12 UTC
Labels: bug
